"""Category and Shape

Revision ID: 086368a0c7ef
Revises: 176bf8c5d67d
Create Date: 2020-06-20 23:08:46.402227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086368a0c7ef'
down_revision = '176bf8c5d67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=30), nullable=True),
    sa.Column('child_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clothes', sa.Column('category_child_id', sa.Integer(), nullable=True))
    op.add_column('clothes', sa.Column('shape_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clothes', 'shape', ['shape_id'], ['id'])
    op.create_foreign_key(None, 'clothes', 'category', ['category_child_id'], ['child_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clothes', type_='foreignkey')
    op.drop_constraint(None, 'clothes', type_='foreignkey')
    op.drop_column('clothes', 'shape_id')
    op.drop_column('clothes', 'category_child_id')
    op.drop_table('shape')
    op.drop_table('category')
    # ### end Alembic commands ###
