"""Clothes

Revision ID: 176bf8c5d67d
Revises: 483d3e632eac
Create Date: 2020-06-20 23:07:57.503234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176bf8c5d67d'
down_revision = '483d3e632eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('recorder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothes_name'), 'clothes', ['name'], unique=False)
    op.create_index(op.f('ix_clothes_timestamp'), 'clothes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothes_timestamp'), table_name='clothes')
    op.drop_index(op.f('ix_clothes_name'), table_name='clothes')
    op.drop_table('clothes')
    # ### end Alembic commands ###
