"""Outfit

Revision ID: 230b4263d8eb
Revises: c52611041c06
Create Date: 2020-06-24 16:36:43.923674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230b4263d8eb'
down_revision = 'c52611041c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('recorder_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_name'), 'outfit', ['name'], unique=False)
    op.create_index(op.f('ix_outfit_timestamp'), 'outfit', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_timestamp'), table_name='outfit')
    op.drop_index(op.f('ix_outfit_name'), table_name='outfit')
    op.drop_table('outfit')
    # ### end Alembic commands ###
