"""Create Category model

Revision ID: 29ca91eedb9a
Revises: deff69599b25
Create Date: 2020-06-25 15:38:23.682025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ca91eedb9a'
down_revision = 'deff69599b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('parent_name', sa.String(length=30), nullable=True),
    sa.Column('child_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_child_id'), 'category', ['child_id'], unique=False)
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_index(op.f('ix_category_child_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
