"""Clothes, Category and Shape

Revision ID: 3c8407c3b4f6
Revises: 483d3e632eac
Create Date: 2020-06-21 17:27:25.954177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8407c3b4f6'
down_revision = '483d3e632eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=30), nullable=True),
    sa.Column('child_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('recorder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothes_name'), 'clothes', ['name'], unique=False)
    op.create_index(op.f('ix_clothes_timestamp'), 'clothes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothes_timestamp'), table_name='clothes')
    op.drop_index(op.f('ix_clothes_name'), table_name='clothes')
    op.drop_table('clothes')
    op.drop_table('shape')
    op.drop_table('category')
    # ### end Alembic commands ###
