"""Forecast

Revision ID: 6eaf3618c364
Revises: 7c5e40c942b8
Create Date: 2020-07-06 09:40:17.661645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaf3618c364'
down_revision = '7c5e40c942b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=True),
    sa.Column('prefecture', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('clothes_index', sa.Integer(), nullable=True),
    sa.Column('weather', sa.String(length=30), nullable=True),
    sa.Column('highest_temp', sa.Integer(), nullable=True),
    sa.Column('lowest_temp', sa.Integer(), nullable=True),
    sa.Column('rain_chance', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_update_time'), 'forecast', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_update_time'), table_name='forecast')
    op.drop_table('forecast')
    # ### end Alembic commands ###
