"""clothes_outfits table

Revision ID: 7c5e40c942b8
Revises: d6cff2f1e846
Create Date: 2020-06-25 16:22:17.026782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5e40c942b8'
down_revision = 'd6cff2f1e846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes_outfits',
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfit.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothes_outfits')
    # ### end Alembic commands ###
