"""Create Clothes model

Revision ID: 820f319b4898
Revises: 908e6ac8c23b
Create Date: 2020-06-25 16:04:39.410646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820f319b4898'
down_revision = '908e6ac8c23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('shape_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothes_category_id'), 'clothes', ['category_id'], unique=False)
    op.create_index(op.f('ix_clothes_name'), 'clothes', ['name'], unique=False)
    op.create_index(op.f('ix_clothes_shape_id'), 'clothes', ['shape_id'], unique=False)
    op.create_index(op.f('ix_clothes_timestamp'), 'clothes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothes_timestamp'), table_name='clothes')
    op.drop_index(op.f('ix_clothes_shape_id'), table_name='clothes')
    op.drop_index(op.f('ix_clothes_name'), table_name='clothes')
    op.drop_index(op.f('ix_clothes_category_id'), table_name='clothes')
    op.drop_table('clothes')
    # ### end Alembic commands ###
