"""Forecast

Revision ID: 83bf2cac084d
Revises: 01ee19bb4653
Create Date: 2020-07-07 11:21:08.332935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83bf2cac084d"
down_revision = "01ee19bb4653"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("clothes_index", sa.Integer(), nullable=True),
        sa.Column("weather", sa.String(length=30), nullable=True),
        sa.Column("highest_temp", sa.Integer(), nullable=True),
        sa.Column("lowest_temp", sa.Integer(), nullable=True),
        sa.Column("rain_chance", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_forecast_location_id"), "forecast", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_forecast_update_time"), "forecast", ["update_time"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forecast_location_id"), table_name="forecast")
    op.drop_index(op.f("ix_forecast_update_time"), table_name="forecast")
    op.drop_table("forecast")
    # ### end Alembic commands ###
