"""Create category_condition

Revision ID: cc13435e45f1
Revises: f1e0070e65de
Create Date: 2020-07-15 17:58:49.572971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc13435e45f1'
down_revision = 'f1e0070e65de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_condition',
    sa.Column('clothes_index_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['clothes_index_id'], ['clothes_index.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_condition')
    # ### end Alembic commands ###
