"""Create Outfit model

Revision ID: d6cff2f1e846
Revises: 820f319b4898
Create Date: 2020-06-25 16:07:47.119073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6cff2f1e846"
down_revision = "820f319b4898"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outfit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("note", sa.String(length=140), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("jacket_id", sa.Integer(), nullable=True),
        sa.Column("top_1_id", sa.Integer(), nullable=True),
        sa.Column("top_2_id", sa.Integer(), nullable=True),
        sa.Column("bottom_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["jacket_id"], ["clothes.id"],),
        sa.ForeignKeyConstraint(["top_1_id"], ["clothes.id"],),
        sa.ForeignKeyConstraint(["top_2_id"], ["clothes.id"],),
        sa.ForeignKeyConstraint(["bottom_id"], ["clothes.id"],),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outfit_name"), "outfit", ["name"], unique=False)
    op.create_index(op.f("ix_outfit_timestamp"), "outfit", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outfit_timestamp"), table_name="outfit")
    op.drop_index(op.f("ix_outfit_name"), table_name="outfit")
    op.drop_table("outfit")
    # ### end Alembic commands ###
