"""Create category_index

Revision ID: fcb227d82bdd
Revises: a341a4704a02
Create Date: 2020-07-15 11:02:31.516995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcb227d82bdd"
down_revision = "a341a4704a02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_index",
        sa.Column("clothes_index_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"],),
        sa.ForeignKeyConstraint(["clothes_index_id"], ["clothes_index.id"],),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category_index")
    # ### end Alembic commands ###
